name: Build Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libfmt-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target install --config ${{env.BUILD_TYPE}}
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{runner.arch}}-${{runner.os}}
        path: ${{github.workspace}}/install/bin/*
        
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static-md

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        runVcpkgInstall: true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target install --config ${{env.BUILD_TYPE}}
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{runner.arch}}-${{runner.os}}
        path: ${{github.workspace}}/install/bin/*
