name: Ubuntu Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libfmt-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target install --config ${{env.BUILD_TYPE}}
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{runner.arch}}-${{runner.os}}
        path: ${{github.workspace}}/install/bin/*
